### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by preexo** [andris9/mailtrain#6]
I get the following error after following the installations instructions:
```
root@msa-web:/var/lib/shared/websites/custom/www/mailtrain-master# NODE_ENV=production npm start

> mailtrain@1.0.0 start /var/lib/shared/websites/custom/www/mailtrain-master
> node index.js


/var/lib/shared/websites/custom/www/mailtrain-master/index.js:7
let config = require('config');
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.29
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! mailtrain@1.0.0 start: `node index.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the mailtrain@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mailtrain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mailtrain
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mailtrain
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/lib/shared/websites/custom/www/mailtrain-master/npm-debug.log
```
/var/lib/shared/websites/custom/www/mailtrain-master/npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'start' ]
2 info using npm@3.8.5
3 info using node@v0.10.29
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle mailtrain@1.0.0~prestart: mailtrain@1.0.0
7 silly lifecycle mailtrain@1.0.0~prestart: no script for prestart, continuing
8 info lifecycle mailtrain@1.0.0~start: mailtrain@1.0.0
9 verbose lifecycle mailtrain@1.0.0~start: unsafe-perm in lifecycle true
10 verbose lifecycle mailtrain@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/lib/shared/websites/custom/www/mailtrain-master/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
11 verbose lifecycle mailtrain@1.0.0~start: CWD: /var/lib/shared/websites/custom/www/mailtrain-master
12 silly lifecycle mailtrain@1.0.0~start: Args: [ '-c', 'node index.js' ]
13 silly lifecycle mailtrain@1.0.0~start: Returned: code: 8  signal: null
14 info lifecycle mailtrain@1.0.0~start: Failed to exec start script
15 verbose stack Error: mailtrain@1.0.0 start: `node index.js`
15 verbose stack Exit status 8
15 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
15 verbose stack     at EventEmitter.emit (events.js:98:17)
15 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
15 verbose stack     at ChildProcess.emit (events.js:98:17)
15 verbose stack     at maybeClose (child_process.js:755:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:822:5)
16 verbose pkgid mailtrain@1.0.0
17 verbose cwd /var/lib/shared/websites/custom/www/mailtrain-master
18 error Linux 3.2.0-4-amd64
19 error argv "node" "/usr/bin/npm" "start"
20 error node v0.10.29
21 error npm  v3.8.5
22 error code ELIFECYCLE
23 error mailtrain@1.0.0 start: `node index.js`
23 error Exit status 8
24 error Failed at the mailtrain@1.0.0 start script 'node index.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the mailtrain package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     node index.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs mailtrain
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls mailtrain
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by jarekkowol** [comment]
I have the same problem


0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart mailtrain@1.0.0
6 info start mailtrain@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info mailtrain@1.0.0 Failed to exec start script
9 error mailtrain@1.0.0 start: `node index.js`
9 error Exit status 8
10 error Failed at the mailtrain@1.0.0 start script.
10 error This is most likely a problem with the mailtrain package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node index.js
10 error You can get their info via:
10 error     npm owner ls mailtrain
10 error There is likely additional logging output above.
11 error System Linux 3.16.0-4-amd64
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "start"
13 error cwd /var/www/mailtrain
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by andris9** [comment]
You seem to be using Node v0.10. The supported version of Node for Mailtrain is v5.10

**Comment by preexo** [comment]
this was it, thanks
