### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by alikuru** [andris9/mailtrain#86]
I'm reading this error through my logs when I start sending a campaign and Mailtrain stuck after sending approximately 50 emails; shows sending in progress on campaign page but delivery and other stats remain the same.

It happens on my own mail server, basically iRedMail with VERP, as described in #81. Haven't changed anything on both Mailtrain and iRedMail side since, other than using a new subscriber list this time. Below is the repeating portion of my log:

    Mail
    Mailtrain-0  Error: socket hang up
    Mailtrain-0 ERR!
    Mailtrain-0
    Mailtrain-0 Mail
    Mailtrain-0      at TLSSocket.onHangUp (_tls_wrap.js:1049:19)
    Mailtrain-0 ERR!
    Mailtrain-0
    Mailtrain-0 Mail
    Mailtrain-0      at TLSSocket.g (events.js:260:16)
    Mailtrain-0 ERR!
    Mailtrain-0
    Mailtrain-0 Mail
    Mailtrain-0      at emitNone (events.js:72:20)
    Mailtrain-0 ERR!
    Mailtrain-0
    Mailtrain-0 Mail
    Mailtrain-0      at TLSSocket.emit (events.js:166:7)
    Mailtrain-0 ERR! Mail     at endReadableNT (_stream_readable.js:921:12)
    Mailtrain-0 ERR! Mail
    Mailtrain-0      at nextTickCallbackWith2Args (node.js:442:9)
    Mailtrain-0 ERR! Mail     at process._tickDomainCallback (node.js:397:17)
    Mailtrain-0 ERR! Mail
    Mailtrain-0  Error: socket hang up
    Mailtrain-0 ERR! Mail     at TLSSocket.onHangUp (_tls_wrap.js:1049:19)
    Mailtrain-0 ERR! Mail     at TLSSocket.g (events.js:260:16)
    Mailtrain-0 ERR! Mail     at emitNone (events.js:72:20)
    Mailtrain-0 ERR! Mail     at TLSSocket.emit (events.js:166:7)
    Mailtrain-0 ERR! Mail     at endReadableNT (_stream_readable.js:921:12)
    Mailtrain-0 ERR! Mail     at nextTickCallbackWith2Args (node.js:442:9)
    Mailtrain-0 ERR! Mail     at process._tickDomainCallback (node.js:397:17)
    Mailtrain-0 ERR! Mail Error: socket hang up
    Mailtrain-0 ERR! Mail     at TLSSocket.onHangUp (_tls_wrap.js:1049:19)
    Mailtrain-0 ERR!
    Mailtrain-0  Mail     at TLSSocket.g (events.js:260:16)
    Mailtrain-0 ERR! Mail     at emitNone (events.js:72:20)
    Mailtrain-0 ERR! Mail     at TLSSocket.emit (events.js:166:7)
    Mailtrain-0 ERR! Mail     at endReadableNT (_stream_readable.js:921:12)
    Mailtrain-0 ERR! Mail     at nextTickCallbackWith2Args (node.js:442:9)
    Mailtrain-0 ERR! Mail     at process._tickDomainCallback (node.js:397:17)
    Mailtrain-0 ERR! Mail Error: socket hang up
    Mailtrain-0 ERR! Mail     at TLSSocket.onHangUp (_tls_wrap.js:1049:19)
    Mailtrain-0 ERR!
    Mailtrain-0  Mail     at TLSSocket.g (events.js:260:16)
    Mailtrain-0 ERR! Mail     at emitNone (events.js:72:20)
    Mailtrain-0 ERR! Mail     at TLSSocket.emit (events.js:166:7)
    Mailtrain-0 ERR! Mail     at endReadableNT (_stream_readable.js:921:12)
    Mailtrain-0 ERR! Mail     at nextTickCallbackWith2Args (node.js:442:9)
    Mailtrain-0 ERR! Mail     at process._tickDomainCallback (node.js:397:17)

Could this be related to the later commits?

**Comment by alikuru** [comment]
Please ignore this. Apparently it's more related to iRedMail than Mailtrain.

I've removed the throttling settings prior sending the campaign, put it back and now everything work as it should.
